_target_: curator.model.MACE
cutoff: ${data.cutoff}
num_interactions: 3
num_elements: null             # will be obtained from species
species: ${data.species}
correlation: 3
hidden_irreps: null
MLP_irreps: null
avg_num_neighbors: null
lmax: 3
parity: True
num_features: 32             # will be inferred from hidden_irreps
num_basis: 8
power: 6
gate: silu
use_cueq: False