
cfg: null
seed: 123
run_path: .
model_path: null
device: cuda
dataset: null
split_file: null
train_set: null
pool_set: null # This can also be a list
batch_size: 100
kernel: full-g
method: lcmd_greedy
n_random_features: 500