  _target_: ase.calculators.vasp.Vasp
  xc: pbe
  encut: 520
  ediff: 1e-05
  ediffg: -0.02
  algo: all
  prec: accurate
  sigma: 0.05
  ibrion: 2
  isif: 2
  ismear: 0
  ispin: 2
  nelmin: 8
  nelm: 400
  lmaxmix: 4
  nsw: 0
  lreal: auto
  ncore: 4
  istart: 0
  isym: 0
  lcharg: False
  lwave: True
  command: mpirun vasp_std
